### PR TITLE
Support for unescaping in trusted messages. Take 2

### PR DESCRIPTION
**Pull request by dimv36**
Hi, how I write in https://github.com/linux-audit/audit-userspace/pull/67, this is adds support for unescaping messages via au_unescape()

### CODE REVIEW

**Comment by stevegrubb** [comment]
I took a quick look. I still don't like the strcmp on the id field. That will make it not generic. But otherwise I think it looks OK. There is a new function added is_int_string(). Is this because some values are decimal rather than hex and it was being picked up as hex?

**Comment by dimv36** [comment]
is_int_string() is used for determining if field value contains only hex symbols, yes.

As for using strcmp(), I can use something else for this cases.

**Comment by stevegrubb** [comment]
I am going to commit this a different way instead of merging a pull request. I like the patch except the strcmp on id. I will remove that part and commit it.

**Comment by stevegrubb** [comment]
This went in as commit 10c64d5. Thanks!

**Pull request closed without merging**
