### PR TITLE
Add support for executable name not equal operator

### PR DESCRIPTION
**Pull request by WOnder93**
Related kernel GH issue: https://github.com/linux-audit/audit-kernel/issues/53

### CODE REVIEW

**Comment by pcmoore** [comment]
@stevegrubb before I merge the kernel patch (see PR above, includes mailing list pointers) I want to make sure you are going to merge the corresponding userspace patch.  Any updates at this point?

**Comment by pcmoore** [comment]
@stevegrubb thanks for looking at the patch.  To answer the "why" question, @rgbriggs was the one who originally captured this request as a GH issue (linked above: linux-audit/audit-kernel#53) based on a mailing list posting (in the kernel issue: [archive link](https://www.redhat.com/archives/linux-audit/2017-June/msg00029.html)).

**Comment by stevegrubb** [comment]
@pcmoore Thanks. OK, I see where this come from. The problem that the user was mentioning is the well known problem where a daemon on RHEL 6 and lower pickup the auid of the user who starts the daemon. Moving to a systemd based OS is the only fix for this problem that I know of. 

So, I guess the use case for this is when you have one specific program that is supposed to have exclusive access a directory and you want to catch anyone else that may try to access it. But it leaves unsolved the case where you have several processes that you want to filter out. For example, you may have a writer process and a reader process that should have exclusive access...no solution for this.

**Comment by WOnder93** [comment]
Hm... now that I think about it, wouldn't all the problems be resolved by allowing the exclude filter to filter by executable name? In fact, there already seems to be a kernel issue filed about this (https://github.com/linux-audit/audit-kernel/issues/54). Or am I misunderstanding how the exclude filter works?

**Comment by rgbriggs** [comment]
On 2018-04-20 08:27, Ondrej Mosnáček wrote:
> Hm... now that I think about it, wouldn't all the problems be resolved by allowing the exclude filter to filter by executable name? In fact, there already seems to be a kernel issue filed about this (https://github.com/linux-audit/audit-kernel/issues/54). Or am I misunderstanding how the exclude filter works?

Yes, this was part of the motivation for filing that issue.

**Comment by WOnder93** [comment]
OK, so @stevegrubb, @pcmoore - would you prefer that I drop the `exe!=` patches and switch to implementing https://github.com/linux-audit/audit-kernel/issues/54 instead?

**Comment by rgbriggs** [comment]
On 2018-04-20 11:08, Ondrej Mosnáček wrote:
> OK, so @stevegrubb, @pcmoore - would you prefer that I drop the
> `exe!=` patches and switch to implementing
> https://github.com/linux-audit/audit-kernel/issues/54 instead?

Is there any reason not to do both?  Having this option not available
would seem surprising to me if I were trying to write rules.

**Comment by pcmoore** [comment]
I agree with @rgbriggs, there doesn't seem to be any harm in implementing both, while only implementing one could leave someone unhappy.

FYI, @WOnder93 I went ahead and assigned linux-audit/audit-kernel/issues/54 to you as well.

**Pull request merged**
