### PR TITLE
Harden systemd service

### PR DESCRIPTION
**Pull request by topimiettinen**
Signed-off-by: Topi Miettinen <toiwoton@gmail.com>

### CODE REVIEW

**Comment by stevegrubb** [comment]
Hello,

First, thanks for looking at making auditd safer/better. The audit daemon can do remote logging via the audisp-remote plugin. It can also aggregate logs sent to it by other audit daemons. Does this systemd policy get inherited by its children? Would this cause third party plugins to have problems doing whatever then need to do?

**Comment by topimiettinen** [comment]
Yes, the children are also restricted. Unfortunately I didn't consider that case, so I'll have to make this much less restrictive. Are there any limits on what the plugins could do? For example, could a plugin reasonably turn off the system in the name of security (thus requiring `@reboot` class of system calls and related `CAP_SYS_BOOT` capabilities)?

**Comment by stevegrubb** [comment]
That is one of the problems, the plugins could do anything. I do not have a full list of all the plugins open source or commercial. And I have some plugin in development that do things like manipulate iptables or kill processes/sessions. If you could divide this into things that should be safe for any use case and things that might be more speculative, then we can look at each on it's own merit. I'm open to improvements, but plugins might do all kinds of things.

**Comment by topimiettinen** [comment]
I don't know SELinux well, but it seems that its "logging" module allows audispd to launch shell, MTA and other executables. More capabilities are also available. That would indicate that it's hard to constrain the plugins much, if at all.

I think the mildest directive in the list is `SystemCallArchitectures=native`, which restricts the system call interface to native versions only (e.g. x86-64 on x86-64, but not i386 or x32). Could it be reasonable to expect use of 32 bit plugins on a 64 bit system?

**Comment by stevegrubb** [comment]
I would not expect a 32 bit plugin on a 64 bit system. There's a small chance it might occur in the commercial space. But even then, I'd still expect a native 64 bit application.

**Comment by topimiettinen** [comment]
Actually, even `SystemCallArchitectures=native` (like many other nice settings) automatically sets `NoNewPrivileges=yes`, which forbids executing any setuid/setgid binaries. I know that at least the notorious `sendmail` was setuid, so even this setting might cause problems.

I'm not sure if there's anything to be done to harden in the general case. Perhaps there would be more opportunities if the architecture could be changed so that audispd could be configured to be launched as a separate systemd service instead of child of auditd?

**Comment by stevegrubb** [comment]
OK. Thanks for looking into this. I guess there is nothing that can be done here. If you have any other improvements, please open an issue or pull request.

**Pull request closed without merging**
